server:
  port: ${APP_PORT:8083}
  servlet:
    context-path: "/flat-service"

openapi:
  title: flat-mcs
  description: Документация flat-mcs API

application:
  file-box-api:
    base-url: http://localhost:8083

spring:
  datasource:
    username: ${DB_USER:flat}
    password: ${DB_PASSWORD:flat}
    url: ${DB_URL:jdbc:postgresql://127.0.0.79:5432/flat_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: public

logging:
  level:
    root: debug
    org.springframework.web.HttpLogging: TRACE
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%logger{36}] - %msg%n"

