spring:
  datasource:
    username: ${DB_USER:deal}
    password: ${DB_PASSWORD:deal}
    url: ${DB_URL:jdbc:postgresql://127.0.0.99:5432/deal_db}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: user
  cloud:
    stream:
      rabbit:
        default:
          producer:
            bindQueue: false
            autoBindDlq: false
            declareExchange: false
            queueNameGroupOnly: true
            exchangeType: fanout
        bindings:
          dealEvents-out-0:
            producer:
              routing-key-expression: headers.routingKey
              exchange-type: direct

      bindings:
        dealEvents-out-0:
          destination: ex.deal

  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

application:
  events:
    enabled: true

logging:
  level:
    org:
      springframework:
        web: info
#!!!!!!!!!!!!!!!!!!!!!!!
server:
  port: ${APP_PORT:8082}
  servlet:
    context-path: "/api-gateway/deal-service"

openapi:
  title: deal-mcs
  description: Документация deal-mcs API
#!!!!!!!!!!!!!!!!!!!!!!

keycloak:
  credentials:
    secret: sp4ndS19BbSgICOcmTG5BC7CVeSEo3u1
  resource: deal-service
  url:
    token-url: https://flat-renta.test.madela.dev/auth/realms/users-realm/protocol/openid-connect/token