server:
  port: ${APP_PORT:8082}
  servlet:
    context-path: "/api-gateway/deal-service"

openapi:
  title: deal-mcs
  description: Документация deal-mcs API

spring:
  datasource:
    username: ${DB_USER:deal}
    password: ${DB_PASSWORD:deal}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/deal_db}
    driver-class-name: org.postgresql.Driver

  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

#    logging:
#      level:
#        root: INFO
#      pattern:
#        console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%logger{36}] - %msg%n"
application:
  events:
    enabled: true

logging:
  level:
    root: debug
    org.springframework.web.HttpLogging: TRACE
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%logger{36}] - %msg%n"
